---
- hosts: all
  become: yes

  tasks:
    - name: Update Package Cache
      apt: update_cache=yes
          
    - name: Update all Packages
      apt: upgrade=dist
    
    - name: Install Apt Control Packages
      apt: name={{item}} state=installed
      with_items:
        - python3-apt

- hosts: router
  become: yes

  tasks:
    - name: Install Hostapd, dhcpd
      apt: name={{item}} state=installed
      with_items:
        - hostapd
        - isc-dhcp-server

    - name: Install Dhcp configuration file.
      copy: src=router/ dest=/etc/dhcp/ owner=root group=root mode=0644
      register: dhcpd

    - name: Restart dhcpd
      service: name=isc-dhcp-server state=restarted enabled=yes
      when: dhcpd.changed

- hosts: db
  become: yes

  tasks:
    - name: Install Postgres 9.4
      apt: name={{item}} state=installed
      with_items:
        - postgresql-9.4
